title Stearlight VM
linux /vmlinuz-virt
initrd /initramfs-virt
options root=LABEL=stearlight-vm rootfstype=ext4 rw quiet loglevel=0 logo.nologo vt.global_cursor_default=0 rd.udev.log_priority=0 console=ttyS0,115200n8 vmwgfx.allowUnsupportedDevices=1
